import { AITool } from "@/types";

export const AI_TOOLS: AITool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "AI Assistant",
    description: "OpenAI's powerful conversational AI.",
    capabilities: ["chat", "coding", "analysis", "image-gen"],
    alternatives: ["claude", "gemini", "perplexity"],
    plans: [
      { name: "Free", price: 0, perUser: false, features: ["Basic chat"] },
      { name: "Plus", price: 20, perUser: false, features: ["GPT-4o", "DALL-E", "Advanced Data Analysis"] },
      { name: "Team", price: 25, perUser: true, features: ["Workspace for teams", "Admin tools"] },
      { name: "Enterprise", price: 60, perUser: true, features: ["SSO", "Advanced security"] },
    ],
  },
  {
    id: "claude",
    name: "Claude",
    category: "AI Assistant",
    description: "Anthropic's safety-focused AI assistant.",
    capabilities: ["chat", "coding", "analysis", "long-context"],
    alternatives: ["chatgpt", "gemini"],
    plans: [
      { name: "Free", price: 0, perUser: false, features: ["Basic access"] },
      { name: "Pro", price: 20, perUser: false, features: ["Claude 3.5 Sonnet", "High usage limits"] },
      { name: "Team", price: 30, perUser: true, features: ["Admin console", "Increased usage"] },
    ],
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "Code Completion",
    description: "The AI Code Editor.",
    capabilities: ["coding", "refactoring", "context-aware"],
    alternatives: ["github-copilot"],
    plans: [
      { name: "Free", price: 0, perUser: false, features: ["200 completions"] },
      { name: "Pro", price: 20, perUser: false, features: ["Unlimited completions", "Claude 3.5 Sonnet"] },
      { name: "Business", price: 40, perUser: true, features: ["Centralized billing", "Privacy mode"] },
    ],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "Code Completion",
    description: "Your AI pair programmer.",
    capabilities: ["coding", "autocomplete"],
    alternatives: ["cursor"],
    plans: [
      { name: "Individual", price: 10, perUser: false, features: ["Standard completions"] },
      { name: "Business", price: 19, perUser: true, features: ["Policy management", "Privacy"] },
      { name: "Enterprise", price: 39, perUser: true, features: ["Custom models", "Knowledge base"] },
    ],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    category: "Image Generation",
    description: "High-quality AI image generator.",
    capabilities: ["image-gen", "art"],
    alternatives: ["dalle", "runway"],
    plans: [
      { name: "Basic", price: 10, perUser: false, features: ["3.3 hr/month GPU"] },
      { name: "Standard", price: 30, perUser: false, features: ["15 hr/month GPU"] },
      { name: "Pro", price: 60, perUser: false, features: ["30 hr/month GPU"] },
      { name: "Mega", price: 120, perUser: false, features: ["60 hr/month GPU"] },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "Research",
    description: "AI-powered search engine.",
    capabilities: ["search", "research", "citations"],
    alternatives: ["chatgpt", "gemini"],
    plans: [
      { name: "Free", price: 0, perUser: false, features: ["Standard search"] },
      { name: "Pro", price: 20, perUser: false, features: ["Claude 3.5 access", "File uploads"] },
      { name: "Enterprise", price: 40, perUser: true, features: ["Team management", "Security"] },
    ],
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "Copywriting",
    description: "AI integrated directly into Notion.",
    capabilities: ["writing", "summarization", "organization"],
    alternatives: ["jasper", "chatgpt"],
    plans: [
      { name: "Add-on", price: 10, perUser: true, features: ["AI inside Notion"] },
    ],
  },
  {
    id: "jasper",
    name: "Jasper",
    category: "Copywriting",
    description: "AI content platform for teams.",
    capabilities: ["writing", "marketing", "brand-voice"],
    alternatives: ["notion-ai", "chatgpt"],
    plans: [
      { name: "Creator", price: 49, perUser: false, features: ["1 seat", "Brand voice"] },
      { name: "Pro", price: 69, perUser: true, features: ["Up to 6 seats", "Campaigns"] },
      { name: "Business", price: 150, perUser: true, features: ["Custom usage"] },
    ],
  },
  {
    id: "runway",
    name: "Runway",
    category: "Video Generation",
    description: "AI video generation and editing.",
    capabilities: ["video-gen", "video-edit"],
    alternatives: ["luma", "pika"],
    plans: [
      { name: "Standard", price: 15, perUser: false, features: ["625 credits"] },
      { name: "Pro", price: 35, perUser: false, features: ["2250 credits"] },
      { name: "Unlimited", price: 95, perUser: false, features: ["Unlimited generations"] },
    ],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "Audio Generation",
    description: "The most realistic AI speech software.",
    capabilities: ["voice-gen", "voice-cloning"],
    alternatives: ["murf"],
    plans: [
      { name: "Starter", price: 5, perUser: false, features: ["30,000 characters"] },
      { name: "Creator", price: 22, perUser: false, features: ["100,000 characters"] },
      { name: "Pro", price: 99, perUser: false, features: ["500,000 characters"] },
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "AI Assistant",
    description: "Google's AI model suite.",
    capabilities: ["chat", "search", "google-integration"],
    alternatives: ["chatgpt", "claude"],
    plans: [
      { name: "Free", price: 0, perUser: false, features: ["Basic Gemini"] },
      { name: "Advanced", price: 20, perUser: false, features: ["Gemini 1.5 Pro"] },
      { name: "Business", price: 20, perUser: true, features: ["Workspace integration"] },
    ],
  },
];
